codecov:
  require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: 94%
        threshold: 0.1%
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no