# Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.

from typing import Any, ContextManager, Optional

class record_function(ContextManager[None]):
    def __init__(self, name: str) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> Optional[bool]: ...
